### ISSUE TITLE
hyperlinks take one entire row

### ISSUE THREAD

**Issue by Grohiik** [Jackbaude/tmc-frontend#2]
you can't make hyperlinks be within other text they just force you to put them on a row by them self, would also be nice with some way of seeing/editing the link while editing the page. Ideally markdown syntax similar to github's comment boxes would be adopted

**Comment by Jackbaude** [comment]
Thanks Grohiik all fixed, pushing later today.

**Comment by Jackbaude** [comment]
https://github.com/Jackbaude/tmc-frontend/commit/9f9ba44502a470ae0e31591f74a2b5f33a74d5e3
